
import type { Metadata } from "next";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";

import AuthProvider from "context/AuthContext";

const baloo = Baloo_Bhaijaan_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taaly!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
